spring:
  datasource:
    url: jdbc:mysql://database-1.cmh6e9rhibog.eu-north-1.rds.amazonaws.com:3306/cloudLabs?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: fireboy1TV999
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      # Hibernate ddl auto (validate, create, create-drop, update)
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mvc:  # the fix for swagger
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080

#  username: root
#  password: fireman9