name: Backend Update

on:
  push:
    branches: main
  repository_dispatch:
    types: [update-backend]
permissions:
  id-token: write
  contents: read
jobs:
    deploy-to-ecr:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-central-1

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Build, tag, and push the image to Amazon ECR
          id: build-image
          env:
            ECR_REPOSITORY: back-end-repository
          run: |
            docker build -t $ECR_REPOSITORY .
            docker tag $ECR_REPOSITORY:latest ${{secrets.ACCOUNT_ID}}.dkr.ecr.eu-central-1.amazonaws.com/$ECR_REPOSITORY:latest
            docker push ${{secrets.ACCOUNT_ID}}.dkr.ecr.eu-central-1.amazonaws.com/$ECR_REPOSITORY:latest
        - name: Update service
          if: github.event_name == 'push'
          run: aws ecs update-service --cluster back-end-cluster --service back-end-service --force-new-deployment
